# - name: "[TITLE]"
# - description: ""
# - credits: "Powered by <a href=\"http://micro.blog/\">Micro.blog</a>."

aboutPage: true

# - markdown: redcarpet
highlighter: pygments

paginate: 20
# - base# - url: "[PATH]/"
domain_# - name: "http://[HOSTNAME]"
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_short# - name: 'your-disqus-shortname'

# Details for the RSS feed generator
# - url: "http://[HOSTNAME]"
# - author: "[TITLE]"
# - user# - name: "[USERNAME]"
# - gravatar_hash: "[GRAVATAR_HASH]"

## - permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post

title: "Joe Duvall"
tagline: ""
description: "Powered by <a href=\"http://micro.blog/\">Micro.blog</a>."
credits: "Powered by <a href=\"http://micro.blog/\">Micro.blog</a>."
baseurl: ""
url: "http://joe.duvall.micro.blog"
markdown: "kramdown"
username: "joeduvall4"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Joe Duvall"
name: "Joe Duvall"
gravatar_hash: "492b074cb0f5e2e9ea55dfab4d89c35f"
avatar: "http://www.gravatar.com/avatar/492b074cb0f5e2e9ea55dfab4d89c35f?s=160"
full_name: "Joe Duvall"
bio: ""
twitter_username: ""
github_username: ""