# # # # # # # #
#   K i k o   #
# # # # # # # #

# - markdown: kramdown

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

title: "Joe Duvall"
tagline: ""
description: "Follow <a href=\"https://micro.blog/joeduvall4\">@joeduvall4 on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/joeduvall4\">@joeduvall4 on Micro.blog</a>."
baseurl: ""
url: "http://micro.blog.joe.duvall.me"
markdown: "kramdown"
username: "joeduvall4"
microblog_user: "joeduvall4"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Joe Duvall"
name: "Joe Duvall"
gravatar_hash: "492b074cb0f5e2e9ea55dfab4d89c35f"
avatar: "https://micro.blog/joeduvall4/avatar.jpg"
full_name: "Joe Duvall"
bio: ""
twitter_username: ""
github_username: ""
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Pacific-New"
site_id: "968"
gems: ["jekyll-paginate"]
itunes_category: "Society & Culture"
itunes_subcategory: "Personal Journals"